# Generated by Django 4.2.3 on 2023-07-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_customuser_referral_code_customuser_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='inviteCode',
        ),
    ]
