# Generated by Django 4.2.3 on 2023-07-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0003_remove_customuser_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.CharField(default='5', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(max_length=30),
        ),
    ]
