# Generated by Django 4.2.3 on 2023-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0004_alter_customuser_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
