# Generated by Django 4.2.3 on 2023-07-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0007_remove_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$JVuCpzflzZlUh1AQPedIjF$JW+hnJpo4Niq7EcNDODGku9hrqcGOqBltVIxsGhXBYE=', max_length=128),
        ),
    ]
