# Generated by Django 4.2.3 on 2023-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0010_customuser_code_customuser_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deliveryAddress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$6QYyad2xDsd7NHmZmUyied$QEWmonsEIM1qIJomwwirAYL9EiReo0rNQ+8YVJ+DGeU=', max_length=128),
        ),
    ]
