# Generated by Django 4.2.3 on 2023-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0013_transaction_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$2GcWnlXoAZS9HGQgJ8qyn6$ApAgEzgikg9fpqrkuxWEdZkXTYVzdTvOED45wmkmgSE=', max_length=128),
        ),
    ]
