# Generated by Django 4.2.3 on 2023-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0014_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$UUKAZ0sSZDzFCNMLhchjPk$LijyPm4oUg7YgjgQDyTNMEfqOEMFBXfnS5YcnZA7gCg=', max_length=128),
        ),
    ]
