# Generated by Django 4.2.3 on 2023-07-23 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0015_transaction_image_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$etDYDNomiSjEQE0IwXziaQ$2avNCCmYlLFMybEnXh4ieIt9ssdrOIuLWUQ8PbUNusU=', max_length=128),
        ),
    ]
