# Generated by Django 4.2.3 on 2023-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0016_transaction_user_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$NUEgzABJACDWELoZGse0oN$TrQtdO+wCqRodYTKPpC7zTMF1NeSMF+uR+7kx0GDZHo=', max_length=128),
        ),
    ]
