# Generated by Django 4.2.3 on 2023-07-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0017_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$MjDSxHdjz16dYCTUhK8NcC$Nr31n41YoCBkQQcTfHW6sHSAXBtVMnYO6Mvm2VsCEZE=', max_length=128),
        ),
    ]
