# Generated by Django 4.2.3 on 2023-07-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0020_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$STLOGisvcMTb7ygEy6cWTg$xoRIvwuYpIcIihKhW7l2J8evQyptrzJz/3FfPHdhMvs=', max_length=128),
        ),
    ]
