# Generated by Django 4.2.3 on 2023-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0021_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$IUE7MspJ3xFtJtCY89oz4x$jETUbpHebHC40ajbMljNlAoQtwfZ5WUk8bR1On4Kqn0=', max_length=128),
        ),
    ]
