# Generated by Django 4.2.3 on 2023-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0022_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$FJMJ46e2LKR8XvzKZVM1Td$Cg0dhHii1xnNdC2RKEUH3aMmPqiiPAv7LWKX0X1xozo=', max_length=128),
        ),
    ]
