# Generated by Django 4.2.3 on 2023-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0023_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$rZNvDMuAytKT4ohMoWPC4U$SBdkMk5UdpSp4s9G4hkJTdc4uFr4DR4n8+CEm4IGOSk=', max_length=128),
        ),
    ]
