# Generated by Django 4.2.3 on 2023-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0024_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$XHW7WsZUXemsrJ4KPlrRta$UCTcX5KiN4tvjxO1n6JlfFbxpr/kogtvb8bV3/hbE4I=', max_length=128),
        ),
    ]
