# Generated by Django 4.2.3 on 2023-07-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0026_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='task',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$isJWgoTzp0w0qIt7LPLkxO$NzuynTr9Hps7HiLCcMrvP5zwmJnt7HsGpccIvlGB4Bw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=50),
        ),
    ]
