# Generated by Django 4.2.3 on 2023-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0027_rename_cost_task_price_remove_task_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$AjnjDyLi40zXkifwiLGh7E$zQvzqimGCLIQiiXerLReei45u/um7Iywkdsf+Amt/RE=', max_length=128),
        ),
    ]
