# Generated by Django 4.2.3 on 2023-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0028_customuser_account_type_alter_customuser_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$a596l10XBIaqPLXFsyWduj$QgCDvCVXLLmWqAfdlH9QhNQ9M1TXy67re549idjR6lo=', max_length=128),
        ),
    ]
