# Generated by Django 4.2.3 on 2023-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0029_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$hx3554LhJ7oVWK2LjJK5eP$AKH11ZL2qK5cLYI+822VVN8A+h3eff2ce0P0DUNbnrY=', max_length=128),
        ),
    ]
