# Generated by Django 4.2.3 on 2023-07-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0030_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$sOrlGwNORcIzUN2vg67Bu2$Ie//0s7VAvzzDyaLY6lDLTouVSoUA31QxlNXBS+dC3k=', max_length=128),
        ),
    ]
