# Generated by Django 4.2.3 on 2023-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0031_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$6RpikNt2yyq2Lw9lgMI4Ed$2ggM1RkRYf9h7H+zK2WxeU6d6a2FYJEfkr6BTPxvU38=', max_length=128),
        ),
    ]
