# Generated by Django 4.2.3 on 2023-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0032_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$MAQGB3TszGkFbFY0hZfYGe$2+1kj3tCblovYVaqdqsLrhp8nbbEJ/25K/LrSRWsEok=', max_length=128),
        ),
    ]
