# Generated by Django 4.2.3 on 2023-07-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0033_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='product_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$mRL3ZFs9QZpJA28zxRJM9d$yB/x4QyKFehbeL8Z6VpjfAILTubVaZmSn1GDMwzNMEU=', max_length=128),
        ),
    ]
