# Generated by Django 4.2.3 on 2023-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0034_task_product_id_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$FuL8SEr9vgOJdI68YLK9nu$Ya3dflPebtcc7H9KKHdtWoAvA6cfIDtdEbYFszSkW9c=', max_length=128),
        ),
    ]
