# Generated by Django 4.2.3 on 2023-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0035_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='earnings',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$PZe1jzqceDxenf9WdXxjqc$Zd5Awxn37MZXSQu3ndZRvBKRWu04tbrEVoRgZaDwl8k=', max_length=128),
        ),
    ]
