# Generated by Django 4.2.3 on 2023-07-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0036_remove_task_earnings_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$8Mw8F4dLIfWOweQHOjtpwy$GTT3a5cF53c7ookysJbdmaqGtB7bEpkri2AjbRHKe0w=', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pending_tasks',
            field=models.ManyToManyField(related_name='pending_tasks', to='appi.task'),
        ),
    ]
