# Generated by Django 4.2.3 on 2023-07-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0037_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$77zPwLk6dibHq2T2P5tSAt$sz5nZdvck3cR7TTvl0XFVB5QBPWOQIj7j2/cNFRuMlI=', max_length=128),
        ),
    ]
