# Generated by Django 4.2.3 on 2023-07-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0038_task_image_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$xHcnCIh41s5RhAiWqvJ3RO$MgGS/lJP+6Jx/XDHdB+kcedC6wJ2XPMO/2CaI0znJsE=', max_length=128),
        ),
    ]
