# Generated by Django 4.2.3 on 2023-07-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0039_remove_task_product_id_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$bWqceD2NPOwg5YU7vlE54A$PA6vQj5M1aE+EajT1ZDSN6doC/vIpmJs0kIN2RUypgs=', max_length=128),
        ),
    ]
