# Generated by Django 4.2.3 on 2023-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0040_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$jX2tM4nLyoLeuE0SzSV3al$dgN1iGqRVJIiFNa7gzix1eb3Ej/kUZYMlw/DoxzgNSc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('frozen', 'Frozen')], default='pending', max_length=20),
        ),
    ]
