# Generated by Django 4.2.3 on 2023-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0041_alter_customuser_password_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$YfTCzOtQf1JQqgfJ5j0xMk$QiBAzWh0LFNgk1J6Qm0fM8U2P+7p5RWJu8kK4KQB5Jg=', max_length=128),
        ),
    ]
