# Generated by Django 4.2.3 on 2023-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0042_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$knzBd6XUXxlOPv4u1FiTPj$xV0ETpI5h2s2RQH832YIYCyx/ibkvalA5YHcUL3mv4Q=', max_length=128),
        ),
    ]
