# Generated by Django 4.2.3 on 2023-07-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0043_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$BjdlwPts0K3xcQiI5jjuIA$ELi+7i54LSfTnFD4Ue4C4ZrJcAPA+ytbuDb72qtyfdg=', max_length=128),
        ),
    ]
