# Generated by Django 4.2.3 on 2023-07-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0044_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$R33chGad7jhW6G1zylMVxN$gsWoRigCm0UBJ2fGxX4pJioyEtnWba/1icTVg3ucKvc=', max_length=128),
        ),
    ]
