# Generated by Django 4.2.3 on 2023-07-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0045_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$8JIOHOdtMxqnlsej8DNTlQ$FvGV2/Bovu55TqyXDjzU9Z0mtSOlVzMhsepL6fo2cS4=', max_length=128),
        ),
    ]
