# Generated by Django 4.2.3 on 2023-07-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0046_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$Zftp7xS2j79DIGnaNnkAnl$YYJHnIVPudgQXKgjQk3iVsxa8Mk9POjhUX2oZNLV2fo=', max_length=128),
        ),
    ]
