# Generated by Django 4.2.3 on 2023-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0047_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$xn603Lj0k6i1lwto01kR68$69JDydUtWnfxBPDMoJXi8G/3izzwMBjqDSrPr+POE6c=', max_length=128),
        ),
    ]
