# Generated by Django 4.2.3 on 2023-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0048_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$CqL0RdRJkrsLjaa016hnuz$+42ZRHC9mH+Czd/XkA0wecYznD/NJIL6xePc8oD/1mw=', max_length=128),
        ),
    ]
