# Generated by Django 4.2.3 on 2023-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0049_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$dvPzGWj8dyHobnyVp8t2CQ$Pyy+rMaGqKE2DuMXTDSSsKCODAuPcQpwBbpNgUzayDg=', max_length=128),
        ),
    ]
