# Generated by Django 4.2.3 on 2023-07-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0051_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$MlGXHCzHuczvLCkBaKpiiZ$gVI8KdHlHRmKpfHIf/Ifa2A4WQVGVxTECpB96vLX2Q4=', max_length=128),
        ),
    ]
