# Generated by Django 4.2.3 on 2023-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0052_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$NL3FsZQI8lOEYyfohIlH2f$Unz7Gcuwq7XEERt31CcHq4dKBOA0NJMoKZ+PiECyh30=', max_length=128),
        ),
    ]
