# Generated by Django 4.2.3 on 2023-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0053_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$ZoXCYfS30i7JlC9bb0U6qa$WyVZbgvbSrjGbm/bLB6YDfCw7Ihb8LyG8f/8n/HtIPs=', max_length=128),
        ),
    ]
