# Generated by Django 4.2.3 on 2023-08-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0055_alter_customuser_password_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$2xsIU0ViCVaEthJOoQVfyK$nw84RUEH4Dq5AW5uXyF7Iv1DF9xhLuZhVJ0YVYfFAvI=', max_length=128),
        ),
    ]
