# Generated by Django 4.2.3 on 2023-08-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0056_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$hxU6lV9LUd9QbIiwREe0JM$pJgZVsAAklpwHzSZdq9pFozvExHK2ElOBaWcAdt+7vs=', max_length=128),
        ),
    ]
