# Generated by Django 4.2.3 on 2023-08-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0057_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$7QP4mX2LSUT3NwG9u5AUz0$/y5WwD5oTTbLrAcsaGOYGW0VVs1b9tMRDA0NLy2EWx4=', max_length=128),
        ),
    ]
