# Generated by Django 4.2.3 on 2023-08-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0060_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('housekeeping', 'Housekeeping'), ('hr', 'Hr')], default='user', max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$5TOwOOtPo4kXVowBsETUZp$pC40+/A0OiZ2tcNAzuQUArbjMiP1MxTP7H5BULsIqXE=', max_length=128),
        ),
    ]
