# Generated by Django 4.2.3 on 2023-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0061_customuser_role_alter_customuser_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$tLhiNHscWzkHEoWi5uMhx9$mDoUOqCRK5Rtk9KC1z7o+i9a0h0b5QsvxwKFhZNytlE=', max_length=128),
        ),
    ]
