# Generated by Django 4.2.3 on 2023-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0062_customuser_country_ip_customuser_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$I1uDcpnd3CAt5YN1ONDaXX$QbVFbTYhwpPIJ22trLduwQFZ5dZ+8dnPMDZRW/NgBHo=', max_length=128),
        ),
    ]
