# Generated by Django 4.2.3 on 2023-08-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0063_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$utN4hKNp5TLtTN3MrFYzqC$arKKwyRrVDMZJa7H2YFrj7NzTaipF/5qirgXMYSOyvs=', max_length=128),
        ),
    ]
