# Generated by Django 4.2.3 on 2023-08-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0064_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='register_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$pCox6kppymMgvmJrJBqB4X$ClSEXYzbz5q7hMSTnPBypij0bY84xTMjAw4YsGkcbeM=', max_length=128),
        ),
    ]
