# Generated by Django 4.2.3 on 2023-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0065_customuser_register_ip_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$Ug7MFuvXIVZ0fHrnNLvgou$0EcVCNrHV0SH3u/JmNIJ/YhOWPg7Epx//a7nlwFsCPs=', max_length=128),
        ),
    ]
