# Generated by Django 4.2.3 on 2023-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0066_task_completed_tasks_count_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$iSjtlAi0CNOVTtc82wwWT1$9KQLAy0vuLwxHuUVpsUS2xEXdzstgTwpWp50irWzRfQ=', max_length=128),
        ),
    ]
