# Generated by Django 4.2.3 on 2023-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0067_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_tasks_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$qJBLTpphJ2pCrjunNaEVPo$LV5uXgeq2jPRMqxkem+sdTg+hSDTT3T6Bg0Jm55yU3w=', max_length=128),
        ),
    ]
