# Generated by Django 4.2.3 on 2023-08-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0068_remove_task_completed_tasks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hold_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$9pHgjLjicXCK45vuVYhODS$M330ua6wEH9ra1j6VcDTU4kmgmM5UnfmWiB07wSYp1M=', max_length=128),
        ),
    ]
