# Generated by Django 4.2.3 on 2023-08-10 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0069_customuser_hold_balance_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$vPRkasM5UyENCbn6x7yfTm$KRfXQipkUoW83AwyKXX16VBhxEU5dc1PvWBGs+iGyjw=', max_length=128),
        ),
    ]
