# Generated by Django 4.2.3 on 2023-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0070_task_created_at_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$raZsqVDgoFtFgrLzqHQ1NI$1nII44aa7/lLFJSlBRrEqzaNquAk4Dyfdi9qRYc2x9M=', max_length=128),
        ),
    ]
