# Generated by Django 4.2.3 on 2023-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0071_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$aYpQFDRzMZKhrnQyhorktj$zYNjgpTANvR14uofRfoUGYjxah/3F287z/IZP1jJl+Q=', max_length=128),
        ),
    ]
