# Generated by Django 4.2.3 on 2023-09-03 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0075_alter_customuser_password_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$g4bkBYDFIfcABAcVuABKwN$ckg2MSpHWI9O4N9YK+U0OKTlT4DnCpnH9nPdk5MjYSw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
