# Generated by Django 4.2.3 on 2023-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0076_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$qurwpayk3QGVub2Rq7WmO5$DRj+vjbpP6NVD3qObFKXm4RstfLHdqh2VFKkkOKc09o=', max_length=128),
        ),
    ]
