# Generated by Django 4.2.3 on 2023-09-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0078_customuser_last_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tasks_left_today',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$f9MRLWEhXVLpvu8JZewzsi$7mByS3msxOjLWq+UmeVCTPHfW4iWPcGkGXjQg0s0gHg=', max_length=128),
        ),
    ]
