# Generated by Django 4.2.3 on 2023-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0079_customuser_tasks_left_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$QjpQPa3fbH8UWaTQMDpjob$gxpVkN1K8iAeIL7SDN/0OPshlkg+6gkm6DqnusFVX98=', max_length=128),
        ),
    ]
