# Generated by Django 4.2.3 on 2023-09-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0081_auto_20230908_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$gsS1OAn5J5hlGA0tO09B0Q$Ox9x2S9jsQp1DFEJhwBOX7oQ/50pbNA51g1381wJLhY=', max_length=128),
        ),
    ]
