# Generated by Django 4.2.3 on 2023-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0082_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('private_key', models.CharField(max_length=66)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$0M98zCmavTCQO6qAhzic06$yZltoOkG4COQH4xOZRhxJGVfRzx8Ja3epnGKaC+9u+k=', max_length=128),
        ),
    ]
