# Generated by Django 4.2.3 on 2023-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0083_hotwallet_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$cewXKIh4b5qbhf4iIAXarj$6qGJWgGyQ2iALAr5PSZIhK304X2vzCHAbv9JU5ya+W0=', max_length=128),
        ),
    ]
