# Generated by Django 4.2.3 on 2023-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0084_task_completion_date_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_tasks_current_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$afqWSus0tPZClUF12HTqAR$RpwMu9JGlaP7CceiuxoQbNoBpF8wRTzFB+jYpsWAjKg=', max_length=128),
        ),
    ]
