# Generated by Django 4.2.3 on 2023-10-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0085_customuser_completed_tasks_current_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$dUBKUMbN1ZThlQsOMVEU6S$X2MbUtSEhxmvWXqX/AkT0WsyeP2D2aB8OiwTtIHW2Ag=', max_length=128),
        ),
    ]
