# Generated by Django 4.2.3 on 2023-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0087_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$4MxFOODdcctyoRLjnSlIHt$93x2Aff0vynBMTFmoLmZqnIfAKM0bW+115FVrqFR7/8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=100),
        ),
    ]
