# Generated by Django 4.2.3 on 2023-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0088_alter_customuser_password_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$atoPiBaq33qVYErmEYBcik$9un0Pf5ug8uCipY56UcGUtnByU+czQOFJe/YC8NWzV0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=265),
        ),
    ]
