# Generated by Django 4.2.3 on 2023-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0091_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$iYjTD7pDVnYEsH0TJC7x6w$23I3tz1re3vxTWbQSk1oK7bT+x3l4VZOsOzO5qRm6Lk=', max_length=128),
        ),
    ]
