# Generated by Django 4.2.3 on 2023-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0092_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$EQwAr61B6In6zAgbHEMaWy$8ADKn2wyDNtxsBJ21GPaw0yqbVI+N9wE6vsAdOQbXQg=', max_length=128),
        ),
    ]
