# Generated by Django 4.2.3 on 2023-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0093_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$y1NqAhrGb6OEzoIZPloD0e$5/ZPn36WlzAWDA1tl5zKfpxeKt3oEXEVl1AXoFYrLOU=', max_length=128),
        ),
    ]
