# Generated by Django 4.2.3 on 2023-10-24 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0094_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$m4JTvvdL79FG76b9jMsMcf$UeCWIWWIMR/OCW/swe4XEeMQqfifTEHFqPVi/94kKYI=', max_length=128),
        ),
        migrations.CreateModel(
            name='TaskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=20)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('price_range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'account_type')},
            },
        ),
    ]
