# Generated by Django 4.2.3 on 2023-10-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0095_alter_customuser_password_taskconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_telegram_notification', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$tqGsqMRufD8KrxU3J7HJm3$g/QZydzKjQYY369z20dbxRETisU+VgkCx8xi9Vbc/z0=', max_length=128),
        ),
    ]
