# Generated by Django 4.2.3 on 2023-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0096_telegramnotificationconfig_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$7WB0s0hSl0KHDfRdUK96tw$z9OQLyvAcf8yFTCci/vZJ3UBNe/8KAkL4pzTwvNgZdM=', max_length=128),
        ),
    ]
