# Generated by Django 4.2.3 on 2023-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0097_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$BHW1yaRpEAC2hhAuJGoBiF$9xt81Dkdl5LRAzLzByVhSLLXN7BdET/lNI1ALzNopUg=', max_length=128),
        ),
    ]
