# Generated by Django 4.2.3 on 2023-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0098_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_unaffordable_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$sIhj7DKUJiKOl7AK4Y8FcA$KbQ2NUKZK5wQU88FcEwwXKalTMDBZHTxp3Clt2Vzlww=', max_length=128),
        ),
    ]
