# Generated by Django 4.2.3 on 2024-01-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0100_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='deliveryAddress',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$nYp4jSA2J6NeBL86LpOhEz$NMHz3RUZkb6VsNLpqZhS5QKt+LUTvXVywgkxL+edkCk=', max_length=128),
        ),
    ]
