# Generated by Django 4.2.3 on 2024-01-28 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0101_alter_customuser_deliveryaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='demo_account_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_demo_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='real_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$jbiHMr5bn69kacv1dDOzas$r1OL+0ZXvFNP4R4S4J1gegVCxI76r62GQmYBpkJHb+Q=', max_length=128),
        ),
    ]
