# Generated by Django 4.2.3 on 2024-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0102_customuser_demo_account_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$tSCw2thOFiHQQazdiE8qei$qMlihjFGILG6/lsVUvN+9gLaW9pqMZSict2tQRBbklA=', max_length=128),
        ),
    ]
